USE testDB;
CREATE TABLE USER_H8 (
   ID_USER INT(5) NOT NULL AUTO_INCREMENT,
   USERNAME_USER VARCHAR(20) NOT NULL,
   EMAIL_USER    VARCHAR(40) NOT NULL,
   PASSWORD_USER VARCHAR(20) NOT NULL,               
   PRIMARY KEY(ID_USER)
);
