CREATE DATABASE IF NOT EXISTS db_hibernate_4;

CREATE TABLE db_hibernate_4.IMPIEGATO(
	ID BIGINT AUTO_INCREMENT,
	NOME VARCHAR(55),
	SALARIO DECIMAL default NULL,
	
    PRIMARY KEY (ID)
);

CREATE TABLE db_hibernate_4.CERTIFICATO(
	ID BIGINT AUTO_INCREMENT,
	NOME_CERTIFICATO VARCHAR(55),
	ID_IMPIEGATO BIGINT,
	
    PRIMARY KEY (ID)
);